Cleanup
Kron4ek/Wine-Builds pull request #88
Opened 2023-03-30 00:07 UTC by liberodark

2023-03-30 22:27 UTC, Kron4ek requested changes

2023-03-30 22:27 UTC, Kron4ek commented on build_wine.sh
> +${BWRAP64} "${BUILD_DIR}"/wine/configure --enable-win64 "${WINE_BUILD_OPTIONS}" --prefix "${BUILD_DIR}"/wine-"${BUILD_NAME}"-amd64
WINE_BUILD_OPTIONS should be without quotes.

2023-03-30 22:27 UTC, Kron4ek commented on build_wine.sh
> +PKG_CONFIG_LIBDIR=/usr/lib/i386-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig ${BWRAP32} "${BUILD_DIR}"/wine/configure "${WINE_BUILD_OPTIONS}" --prefix "${BUILD_DIR}"/wine-"${BUILD_NAME}"-x86
WINE_BUILD_OPTIONS should be without quotes.

2023-03-30 22:27 UTC, Kron4ek commented on build_wine.sh
> +			"${staging_patcher[@]}" "${STAGING_ARGS}"
STAGING_ARGS should be without quotes.

2023-04-02 07:41 UTC, merged

2023-04-04 10:08 UTC, liberodark commented
Hi,
Sorry I was unfortunately unavailable. 
Thanks for correcting the errors.